# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: saint-dominic_development

 
test:
  <<: *default
  database: saint-dominic_test


production:
  <<: *default
  database: saint-dominic_production
  username: saint-dominic
  password: <%= ENV['SAINT-DOMINIC_DATABASE_PASSWORD'] %>
